# Generated by Django 3.1.7 on 2021-03-12 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offices', models.IntegerField()),
                ('board_rooms', models.IntegerField()),
                ('toilets', models.IntegerField()),
                ('kitchens', models.IntegerField()),
                ('reception_areas', models.IntegerField()),
                ('parking_bays', models.IntegerField()),
                ('generator', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=20)),
                ('backup_water', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True)),
                ('under_roof_sqm', models.IntegerField()),
                ('rates_taxes', models.IntegerField()),
                ('levis', models.IntegerField()),
                ('fibre', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True)),
                ('security', models.CharField(max_length=100)),
                ('business_or_retail', models.CharField(choices=[('Business', 'Business'), ('Retail', 'Retail')], default='Business', max_length=20)),
                ('auction_date', models.DateTimeField()),
                ('province', models.CharField(choices=[('Eastern Cape', 'Eastern Cape'), ('Freestate', 'Freestate'), ('Gauteng', 'Gauteng'), ('Kwazulu-Natal', 'Kwazulu-Natal'), ('Limpopo', 'Limpopo'), ('Mpumulanga', 'Mpumulanga'), ('North West', 'North West'), ('Northen Cape', 'Northen Cape'), ('Western Cape', 'Western Cape')], max_length=20)),
                ('town_or_city', models.CharField(max_length=100)),
                ('agent_name', models.CharField(max_length=50)),
                ('agent_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.agent', to_field='email')),
            ],
        ),
    ]
