# Generated by Django 3.1.7 on 2021-03-17 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercial',
            name='main_image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commercial',
            name='start_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Extra_Images_Commercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial_properties.commercial', verbose_name='Commercial')),
            ],
        ),
    ]
