# Generated by Django 3.1.7 on 2021-04-08 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_properties', '0002_auto_20210317_0906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commercial',
            options={'ordering': ('auction_date',)},
        ),
    ]
