# Generated by Django 3.1.7 on 2021-04-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_apartment_bid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'ordering': ('auction_date',)},
        ),
        migrations.AddField(
            model_name='apartment',
            name='street_address',
            field=models.CharField(default='12 Boek', max_length=100),
            preserve_default=False,
        ),
    ]
