# Generated by Django 3.2.3 on 2021-05-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_auto_20210408_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='property_type',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='auction_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='bath_rooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='bedrooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='carport',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='garages',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='laundry',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='levis',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='living_rooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='outside_space',
            field=models.CharField(choices=[('Balcony', 'Balcony'), ('Garden', 'Garden'), ('None', 'None')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='pool',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='province',
            field=models.CharField(choices=[('Eastern Cape', 'Eastern Cape'), ('Freestate', 'Freestate'), ('Gauteng', 'Gauteng'), ('Kwazulu-Natal', 'Kwazulu-Natal'), ('Limpopo', 'Limpopo'), ('Mpumulanga', 'Mpumulanga'), ('North West', 'North West'), ('Northen Cape', 'Northen Cape'), ('Western Cape', 'Western Cape')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='rates_taxes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='security',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='street_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='town_or_city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='under_roof_sqm',
            field=models.IntegerField(null=True),
        ),
    ]
