# Generated by Django 3.1.7 on 2021-04-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectional_industrial_properties', '0002_auto_20210317_0906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectional_industrial_property',
            options={'ordering': ('auction_date',)},
        ),
        migrations.AddField(
            model_name='sectional_industrial_property',
            name='street_address',
            field=models.CharField(default='text field cumming on faces of ', max_length=100),
            preserve_default=False,
        ),
    ]
