# Generated by Django 3.1.7 on 2021-04-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('townhouses', '0002_auto_20210317_0906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='townhouse',
            options={'ordering': ('auction_date',)},
        ),
        migrations.AddField(
            model_name='townhouse',
            name='street_address',
            field=models.CharField(default='6ix9ine', max_length=100),
            preserve_default=False,
        ),
    ]
