# Generated by Django 3.1.7 on 2021-03-12 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoning', models.CharField(choices=[('Residential 1', 'Residential 1'), ('Residential 2', 'Residential 2'), ('Residential 3', 'Residential 3'), ('Commercial-Business', 'Commercial-Business'), ('Commercial-Retail', 'Commercial-Retail'), ('Industrial', 'Industrial'), ('Agriculture', 'Agriculture'), ('Residential', 'Residential')], default='Industrial', max_length=20)),
                ('services', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=20)),
                ('land_sqm', models.IntegerField()),
                ('rates_taxes', models.IntegerField()),
                ('auction_date', models.DateTimeField()),
                ('province', models.CharField(choices=[('Eastern Cape', 'Eastern Cape'), ('Freestate', 'Freestate'), ('Gauteng', 'Gauteng'), ('Kwazulu-Natal', 'Kwazulu-Natal'), ('Limpopo', 'Limpopo'), ('Mpumulanga', 'Mpumulanga'), ('North West', 'North West'), ('Northen Cape', 'Northen Cape'), ('Western Cape', 'Western Cape')], max_length=20)),
                ('town_or_city', models.CharField(max_length=100)),
                ('agent_name', models.CharField(max_length=50)),
                ('agent_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.agent', to_field='email')),
            ],
            options={
                'verbose_name_plural': 'Land',
            },
        ),
    ]
