# Generated by Django 3.1.7 on 2021-03-17 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('industrial_properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tonnes', models.IntegerField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industrial_properties.industrial_property', verbose_name='Crane')),
            ],
        ),
    ]
