# Generated by Django 3.1.7 on 2021-03-17 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('industrial_properties', '0002_crane'),
    ]

    operations = [
        migrations.AddField(
            model_name='industrial_property',
            name='main_image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='industrial_property',
            name='start_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Extra_Images_Industrial_Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('industrial_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industrial_properties.industrial_property', verbose_name='LaIndustrial_Propertynd')),
            ],
        ),
    ]
