# Generated by Django 3.1.7 on 2021-04-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industrial_properties', '0003_auto_20210317_0906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industrial_property',
            options={'ordering': ('auction_date',), 'verbose_name_plural': 'Industrial Properties'},
        ),
        migrations.AddField(
            model_name='industrial_property',
            name='street_address',
            field=models.CharField(default='eh', max_length=100),
            preserve_default=False,
        ),
    ]
